[package]
name = "rustywin"
version = "0.0.1"
authors = ["Gian-Carlo Pascutto <gcp@sjeng.org>"]
readme = "README.md"
license = "MPL-2.0"

[dependencies]
clippy = { version = "*", optional = true }
log = "0.3"
env_logger = "0.4"
nix = "0.7"
libc = "0.2"
itertools = "0.5"

[features]
default = []
